- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
- name: "install Docker."
  become: true
  apt:
    name: ["docker.io"]
    update_cache: yes
- name: "install conntrack for minikube."
  become: true
  apt:
    name: ["conntrack"]
    update_cache: yes
- name: "install curl,wget,aot-transport-https."
  become: true
  apt:
    name: ["curl","wget","apt-transport-https"]
    update_cache: yes
- name: "install minikube-1"
  become: false
  get_url: 
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /home/ubuntu
    mode: 0755
- name: "install kubectl-1"
  become: false
  get_url: 
    url: https://storage.googleapis.com/kubernetes-release/release/v1.24.0/bin/linux/amd64/kubectl
    dest: /home/ubuntu
    mode: 0755
- name: "install minikube-2"
  become: true
  command: mv minikube-linux-amd64 /usr/local/bin/minikube
- name: "install kubectl-2"
  become: true
  command: mv kubectl /usr/local/bin/kubectl
- name: "change permission of docker loc file"
  become: true
  command: chmod o+rw /var/run/docker.sock
- name: "minikube start"
  become: false
  command: minikube start
- name: "sleep 60"
  become: false
  command: sleep 60
- name: "Create docker deployment"
  become: false
  command: kubectl create deployment capstoneproj --image=pramation/capstoneproj --replicas=2 --port=8080
- name: "sleep 60"
  become: false
  command: sleep 60
- name: "Expose port to external-ip"
  become: false
  command: kubectl expose deployment/capstoneproj --type="NodePort" --port 8080  --external-ip='3.88.45.116'  --target-port=8080
- name: "sleep 30"
  become: false
  command: sleep 30
