- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
- name: "install Docker."
  become: true
  apt:
    name: ["docker.io"]
    update_cache: yes
- name: "install conntrack for minikube."
  become: true
  apt:
    name: ["conntrack"]
    update_cache: yes
- name: "install curl,wget,aot-transport-https."
  become: true
  apt:
    name: ["curl","wget","apt-transport-https"]
    update_cache: yes
- name: "install minikube-1"
  become: false
  get_url: 
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /home/ubuntu
    mode: 0755
- name: "install kubectl-1"
  become: false
  get_url: 
    url: https://storage.googleapis.com/kubernetes-release/release/v1.24.0/bin/linux/amd64/kubectl
    dest: /home/ubuntu
    mode: 0755
- name: "install minikube-2"
  become: true
  command: mv minikube-linux-amd64 /usr/local/bin/minikube
- name: "install kubectl-2"
  become: true
  command: mv kubectl /usr/local/bin/kubectl
