- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
- name: "install Docker."
  become: true
  apt:
    name: ["docker"]
    update_cache: yes
- name: "install conntrack."
  become: true
  apt:
    name: ["conntrack"]
    update_cache: yes
- name: "install curl,wget,aot-transport-https."
  become: true
  apt:
    name: ["curl","wget","apt-transport-https"]
    update_cache: yes
- name: "install minikube"
  become: true
  get_url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
