- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
- name: "install Docker."
  become: true
  apt:
    name: ["docker"]
    update_cache: yes
- name: "install conntrack."
  become: true
  apt:
    name: ["conntrack"]
    update_cache: yes
