version: 2.1 
commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID
    parameters:
      workflow-id:
        type: string
        default: "devops-capstone-${CIRCLE_WORKFLOW_ID:0:7}"
    steps:
      - run:
          name: Destroy environment and delete s3 bucket
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name devops-capstone-${CIRCLE_WORKFLOW_ID:0:7}
            #aws s3 rm s3://udapeople-project4-${CIRCLE_WORKFLOW_ID:0:7} --recursive
            #aws s3 rb s3://udapeople-project4-${CIRCLE_WORKFLOW_ID:0:7} --force

jobs:
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: install required utilities
          command: |
             yum install tar -y
             yum install gzip -y
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/build_server.yml \
              --tags project="devops-capstone-${CIRCLE_WORKFLOW_ID:0:7}" \
              --stack-name "devops-capstone-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:Name,Values=devops-capstone-${CIRCLE_WORKFLOW_ID:0:7}" \
              --output text >> .circleci/inventory.txt
            cat .circleci/inventory.txt       
      - persist_to_workspace:
          root: .
          paths:
            - ./.circleci/inventory.txt
          command: |
            cat .circleci/inventory.txt
      - destroy-environment:
          workflow-id: "devops-capstone-${CIRCLE_WORKFLOW_ID:0:7}"    
  nothing:  
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: install required utilities
          command: |
             echo "hello world"
      - run:
          name: Deploy backend
          no_output_timeout: 5m
          command: |
            cd .circleci/ansible
            echo "Contents  of the inventory.txt file is --------"
            cat inventory.txt
            export ANSIBLE_HOST_KEY_CHECKING=false
            ansible-playbook -i inventory.txt deploy-app.yml 
  lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "deploy_app/requirements.txt" }}
          - v1-dependencies-  
      
      - run:
          name: "install dependencies"
          command: |
            
            python3 -m venv .devops_capstone
            source .devops_capstone/bin/activate
            cd deploy_app
            uname -a
            make install
      - save_cache:
          paths:
           - ./.devops_capstone
          key: v1-dependencies-{{ checksum "deploy_app/requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
             . .devops_capstone/bin/activate
             cd deploy_app
             make lint 
  build_docker:
    docker:
      - image: docker:17.05.0-ce-git
    steps:   
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: "build docker Image"
          command: |
              cd deploy_app
              echo "Building Docker Image..."
              docker build --tag=capstoneproj /root/project/deploy_app
              echo "List Image..."
              docker image ls
      - run:
          name: "upload docker Image"
          command: |

              # Create dockerpath
              dockerpath="pramation/capstoneproj" 
              # Authenticate & tag
              echo "Docker ID and Image: $dockerpath"
              docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD && docker image tag capstoneproj $dockerpath
              # Push image to a docker repository
              docker image push $dockerpath
      - run:
          name: "Run docker Image"
          command: |
              cd deploy_app
              echo "Run Docker Image..."
              #docker run -p 8080:8080 capstoneproj 


 
workflows:
  default:
    jobs:
      - nothing
     # - deploy-infrastructure
     # - lint
     # - build_docker 
